config/routes.rb
Rails.application.routes.draw do
 
  # get '/instalacoes_sensores/:installation_id', to: "sensor_installation#index", as: :sensor_installation
  # get '/instalacoes_sensores/:installation_id/new', to: "sensor_installation#new"
  

  resources :installations, path: "instalacoes" do
    patch '/sensores/:id',to: "sensor_installation#update" ,as: "installation_sensors"
    resources :sensor_installation, path: "sensores", as: :sensors
  end
  resources :equipment, path: "equipamentos" do
    patch '/sensores/:id',to: "sensor_equipment#update" ,as: "equipment_sensors"
    resources :sensor_equipment, path: "sensores", as: :sensors
  end
  resources :installations, path: :instalacoes
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'installations#index'
end

app/models/installation.rb
class Installation < ApplicationRecord
  validates :name, :campus, :complement, presence: true
  has_many :sensors, as: :monitorable
  belongs_to :user
  has_many :equipments

  def length_recursive
    sum = sensors.length
    equipments.each do |e|
      sum += e.sensors.length
    end
    sum
  end
end

app/controllers/installations_controller.rb
class InstallationsController < ApplicationController
  before_action :set_installation, only: [:show, :edit, :update, :destroy]

  # GET /installations
  # GET /installations.json
  def index
    @installations = Installation.all
  end

  # GET /installations/1
  # GET /installations/1.json
  def show
  end

  # GET /installations/new
  def new
    @installation = Installation.new
  end

  # GET /installations/1/edit
  def edit
  end

  # POST /installations
  # POST /installations.json
  def create
    @installation = Installation.new(installation_params)

    respond_to do |format|
      if @installation.save
        format.html { redirect_to @installation, notice: 'Instituição foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @installation }
      else
        format.html { render :new }
        format.json { render json: @installation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /installations/1
  # PATCH/PUT /installations/1.json
  def update
    respond_to do |format|
      if @installation.update(installation_params)
        format.html { redirect_to @installation, notice: 'Instituição foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @installation }
      else
        format.html { render :edit }
        format.json { render json: @installation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /installations/1
  # DELETE /installations/1.json
  def destroy
    @installation.destroy
    respond_to do |format|
      format.html { redirect_to installations_url, notice: 'Installation foi destruido com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_installation
      @installation = Installation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def installation_params
      params.require(:installation).permit(:name, :user_id, :campus, :complement)
    end
end

app/helpers/installations_helper.rb
module InstallationsHelper
end

app/views/installations/_form.html.erb
<%= form_with(model: installation, local: true) do |form| %>
  <% if installation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(installation.errors.count, "error") %> prohibited this installation from being saved:</h2>

      <ul>
      <% installation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :campus %>
    <%= form.text_field :campus %>
  </div>

  <div class="field">
    <%= form.label :complement %>
    <%= form.text_field :complement %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/installations/edit.html.erb
<h1>Editing Installation</h1>

<%= render 'form', installation: @installation %>

<%= link_to 'Show', @installation %> |
<%= link_to 'Back', installations_path %>

app/views/installations/index.html.erb
<p id="notice"><%= notice %></p>
<div class="img-container">
  <%= image_tag("logo.png", :alt => "Logo")%>
</div>
<h1 class="title">Instalações</h1>
<section>
  <% @installations.each do |installation| %>
    <%= link_to  installation,  class: "card" do%>
      <div class="container">
        <ul>
          <div class="installation_detail">
            <li>Instalação: <%= installation.name %></li>
          </div>
          <div class="installation_detail">
            <li >Usuário responsável: <%= installation.user.name %></li>
          </div>
          <div class="installation_detail">
            <li >Campus: <%= installation.campus %></li>
          </div>
          <div class="installation_detail">
            <li >Numeros de sensores diretos: <%= installation.sensors.length %></li>
          </div>
          <div class="installation_detail">
            <li >Numeros de sensores indiretos: <%= installation.length_recursive %></li>
          </div>
          <% if installation.complement %>
            <div class="installation_detail">
              <li>Detalhes: <%= installation.complement %></li>
            </div>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
</section>
<div>
  <%= link_to 'New Installation', new_installation_path %>
</div>
<%
=begin%>
<li><%= link_to 'Show', installation %></li>
<li><%= link_to 'Edit', edit_installation_path(installation) %></li>
<li><%= link_to 'Destroy', installation, method: :delete, data: { confirm: 'Are you sure?' } %></li>
<%
=end%>

app/views/installations/new.html.erb
<h1>New Installation</h1>

<%= render 'form', installation: @installation %>

<%= link_to 'Back', installations_path %>

app/views/installations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="img-container">
  <%= image_tag("logo.png", :alt => "Logo")%>
</div>

<h1 class="title">Equipamentos da sala</h1>
<h2 class="title">Sala: <%=@installation.name%></h2>
<%= link_to  "sensores da instalação", installation_sensors_path(@installation) %>
<% @installation.equipments.each do |equipment|%>
  <%= link_to  equipment do%>
    <div class="container card">
      <ul>
        <div class="installation_detail">
          <li>Equipamento: <%= equipment.name %></li>
        </div>
    </div>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_installation_path(@installation) %> |
<%= link_to 'Back', installations_path %>