config/routes.rb
Rails.application.routes.draw do
 
  # get '/instalacoes_sensores/:installation_id', to: "sensor_installation#index", as: :sensor_installation
  # get '/instalacoes_sensores/:installation_id/new', to: "sensor_installation#new"
  

  resources :installations, path: "instalacoes" do
    patch '/sensores/:id',to: "sensor_installation#update" ,as: "installation_sensors"
    resources :sensor_installation, path: "sensores", as: :sensors
  end
  resources :equipment, path: "equipamentos" do
    patch '/sensores/:id',to: "sensor_equipment#update" ,as: "equipment_sensors"
    resources :sensor_equipment, path: "sensores", as: :sensors
  end
  resources :installations, path: :instalacoes
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'installations#index'
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :installation
  validates :name, presence: true
  has_many :sensors, as: :monitorable
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]

  # GET /equipment
  # GET /equipment.json
  def index
    @equipments = Equipment.all
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
  end

  # GET /equipment/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Equipamento foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @equipment }
      else
        format.html { render :new }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to @equipment, notice: 'Equipamento foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipment_index_url, notice: 'Equipment foi destruido com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipment_params
      params.require(:equipment).permit(:name, :installation_id)
    end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_form.html.erb
<%= form_with(model: equipment, local: true) do |form| %>
  <% if equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

      <ul>
      <% equipment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :installation_id %>
    <%= form.text_field :installation_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/equipment/edit.html.erb
<h1>Editing Equipment</h1>

<%= render 'form', equipment: @equipment %>

<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>

app/views/equipment/index.html.erb
<p id="notice"><%= notice %></p>
<head>
  <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
</head>
<div class="img-container">
  <%= image_tag("logo.png", :alt => "Logo")%>
</div>
<h1 class="title">Equipamentos</h1>
<% @equipments.each do |equipment| %>
  <div class="container card">
    <ul>
      <li class="equipment-name">Nome do Equipamento: <%= equipment.name %></li>
      <li>Sala: <%= equipment.installation.name %></li>
      <li >Numeros de sensores indiretos: <%= installation.length_recursive %></li>
    </ul>
    <td><%= link_to 'Show', equipment %></td>
    <td><%= link_to 'Edit', edit_equipment_path(equipment) %></td>
    <td><%= link_to 'Destroy', equipment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </div>
<% end %>
<div class="link-div">
  <%= link_to 'Novo Equipamento', new_equipment_path %>
</div>

app/views/equipment/new.html.erb
<h1>New Equipment</h1>

<%= render 'form', equipment: @equipment %>

<%= link_to 'Back', equipment_index_path %>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>
<div class="img-container">
  <%= image_tag("logo.png", :alt => "Logo")%>
</div>
<h1 class="title">Equipamento</h1>
<div class="container">
  <h2><%= @equipment.name %></h2>
  <div class="sensores">
    
    
    <ul>
      <% @equipment.sensors.each do |sensor|%>
        <li><span><%=sensor.identifier%></span><span>dados</span></li>
      <% end %>
      </ul>
  </div>
  <div class="link-div">
    <%= link_to 'Editar', edit_equipment_path(@equipment) %>
    <%= link_to 'Voltar', (@equipment.installation) %>
  </div>
</div>