config/routes.rb
Rails.application.routes.draw do
 
  # get '/instalacoes_sensores/:installation_id', to: "sensor_installation#index", as: :sensor_installation
  # get '/instalacoes_sensores/:installation_id/new', to: "sensor_installation#new"
  

  resources :installations, path: "instalacoes" do
    patch '/sensores/:id',to: "sensor_installation#update" ,as: "installation_sensors"
    resources :sensor_installation, path: "sensores", as: :sensors
  end
  resources :equipment, path: "equipamentos" do
    patch '/sensores/:id',to: "sensor_equipment#update" ,as: "equipment_sensors"
    resources :sensor_equipment, path: "sensores", as: :sensors
  end
  resources :installations, path: :instalacoes
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'installations#index'
end

app/controllers/sensor_equipment_controller.rb
# frozen_string_literal: true

class SensorEquipmentController < ApplicationController
  before_action :set_equipment, only: %i[show create edit update destroy index]
  before_action :set_sensor, only: %i[show edit update destroy]


  def show; end

  def new
    @sensor = Sensor.new
  end

  def index; end

  def edit; end

  def update
    respond_to do |format|
      @sensor.monitorable = @equipment
      if @sensor.update(sensor_params)
        format.html { redirect_to equipment_sensors_path(@sensor.monitorable, @sensor), notice: 'Sensor foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @sensor = Sensor.new(sensor_params)
    @sensor.monitorable = @equipment

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to equipment_sensors_path(@sensor.monitorable), notice: 'Sensor foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy    
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to equipment_sensors_path, notice: 'Sensor foi destruido com sucesso' }
      format.json { head :no_content }
    end
  end

  private

  def set_equipment
    @equipment = Equipment.find(params[:equipment_id])
  end

  def set_sensor
    @sensor = Sensor.find(params[:id])
  end

  def sensor_params
    params.require(:sensor).permit(:identifier)
  end
end

app/helpers/sensor_equipment_helper.rb
module SensorEquipmentHelper
end

app/views/sensor_equipment/_form.html.erb
<%= form_with(model: sensor, url: equipment_sensor_path, local: true) do |form| %>
  <% if sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sensor.errors.count, "error") %> prohibited this monitoring from being saved:</h2>

      <ul>
      <% sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :identifier %>
    <%= form.text_field :identifier %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sensor_equipment/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Show', equipment_sensor_path(@equipment,@sensor) %> |
<%= link_to 'Back', equipment_sensors_path(@equipment) %>

app/views/sensor_equipment/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sensores da Instalação <%= @equipment.name %></h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipment.sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.identifier %></td>
        <td><%= link_to  "editar", edit_equipment_sensor_path(@equipment, sensor) %></td>
        <td><%= link_to  "delete", equipment_sensor_path(@equipment, sensor), method: :delete  %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor', new_equipment_sensor_path %>

app/views/sensor_equipment/new.html.erb
<h1>New Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Back', equipment_sensors_path %>

app/views/sensor_equipment/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identifier:</strong>
  <%= @sensor.identifier %>
</p>

<%= link_to 'Edit', edit_equipment_sensor_path(@equipment,@sensor) %> |
<%= link_to 'Back', equipment_sensors_path(@equipment) %>