config/routes.rb
Rails.application.routes.draw do
 
  # get '/instalacoes_sensores/:installation_id', to: "sensor_installation#index", as: :sensor_installation
  # get '/instalacoes_sensores/:installation_id/new', to: "sensor_installation#new"
  

  resources :installations, path: "instalacoes" do
    patch '/sensores/:id',to: "sensor_installation#update" ,as: "installation_sensors"
    resources :sensor_installation, path: "sensores", as: :sensors
  end
  resources :equipment, path: "equipamentos" do
    patch '/sensores/:id',to: "sensor_equipment#update" ,as: "equipment_sensors"
    resources :sensor_equipment, path: "sensores", as: :sensors
  end
  resources :installations, path: :instalacoes
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'installations#index'
end

app/models/sensor.rb
class Sensor < ApplicationRecord
  validates :identifier, presence: true, uniqueness: true
  belongs_to :monitorable, polymorphic: true
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor foi destruido com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:identifier)
    end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= form_with(model: sensor, local: true) do |form| %>
  <% if sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :identifier %>
    <%= form.text_field :identifier %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sensors</h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.identifier %></td>
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor', new_sensor_path %>

app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identifier:</strong>
  <%= @sensor.identifier %>
</p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>